#!/bin/bash

# scan-project-state.sh
# Fires on sessionStart. Scans all final/ docs for frontmatter status, detects cross-layer dependencies,
# and writes a compact state summary to .cursor/session-state.md for consumption by the rule.

set -euo pipefail

REPO_ROOT="${1:-.}"
STATE_FILE="${REPO_ROOT}/.cursor/session-state.md"
LAYERS_DIR="${REPO_ROOT}/layers"
TODAY=$(date +%Y-%m-%d)

# Ensure .cursor directory exists
mkdir -p "$(dirname "$STATE_FILE")"

# Initialize state file
cat > "$STATE_FILE" <<'EOF'
# Session State

Auto-generated by scan-project-state.sh on session start.
Surfaces docs needing review, updates, or attention.

EOF

# Track what we find
NEEDS_REVIEW=()
NEEDS_UPDATE=()
IN_PROGRESS=()
MISSING_CROSS_LAYER=()
STALE_DOCS=()

# Scan all final/ documents
while IFS= read -r -d '' doc; do
    # Extract frontmatter
    if [[ "$doc" =~ ^---$ ]]; then
        # Simple frontmatter extraction (assumes YAML front matter)
        status=$(grep "^status:" "$doc" 2>/dev/null | head -1 | cut -d: -f2 | xargs)
        last_updated=$(grep "^last_updated:" "$doc" 2>/dev/null | head -1 | cut -d: -f2 | xargs)
        relates_to=$(grep "^relates_to:" "$doc" 2>/dev/null | head -1 | cut -d: -f2- | xargs)

        case "$status" in
            needs_review)
                NEEDS_REVIEW+=("$doc")
                ;;
            needs_update)
                NEEDS_UPDATE+=("$doc")
                ;;
            in_progress)
                IN_PROGRESS+=("$doc")
                ;;
        esac

        # Check if document is stale (last_updated is more than 30 days old)
        if [[ -n "$last_updated" ]]; then
            last_date=$(date -d "$last_updated" +%s 2>/dev/null || echo 0)
            today_seconds=$(date -d "$TODAY" +%s)
            days_old=$(( (today_seconds - last_date) / 86400 ))
            if [[ $days_old -gt 30 ]]; then
                STALE_DOCS+=("$doc (last updated $last_updated, $days_old days ago)")
            fi
        fi
    fi
done < <(find "$LAYERS_DIR" -path "*/final/*.md" -print0 2>/dev/null)

# Append summaries to state file
{
    echo ""
    echo "## Needs Review"
    if [[ ${#NEEDS_REVIEW[@]} -eq 0 ]]; then
        echo "None — all docs are current."
    else
        for doc in "${NEEDS_REVIEW[@]}"; do
            echo "- $doc"
        done
    fi

    echo ""
    echo "## Needs Update"
    if [[ ${#NEEDS_UPDATE[@]} -eq 0 ]]; then
        echo "None — no updates required."
    else
        for doc in "${NEEDS_UPDATE[@]}"; do
            echo "- $doc"
        done
    fi

    echo ""
    echo "## In Progress"
    if [[ ${#IN_PROGRESS[@]} -eq 0 ]]; then
        echo "None — no active work."
    else
        for doc in "${IN_PROGRESS[@]}"; do
            echo "- $doc"
        done
    fi

    echo ""
    echo "## Stale Docs (30+ days old)"
    if [[ ${#STALE_DOCS[@]} -eq 0 ]]; then
        echo "None — all docs are recent."
    else
        for doc in "${STALE_DOCS[@]}"; do
            echo "- $doc"
        done
    fi

    echo ""
    echo "---"
    echo "Generated: $TODAY"
} >> "$STATE_FILE"

exit 0
